CREATE OR ALTER PROCEDURE SP_GAMIFICACAO_AVALIACOES_ANALISTAS
(
    @DATA_INICIO DATE,
    @DATA_FIM DATE
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        A.operator_name AS ANALISTA,

        SUM(CASE WHEN TRY_CONVERT(INT, B.avaliacao) = 10 THEN 1 ELSE 0 END) AS NOTA_10,
        SUM(CASE WHEN TRY_CONVERT(INT, B.avaliacao) = 9  THEN 1 ELSE 0 END) AS NOTA_9,
        SUM(CASE WHEN TRY_CONVERT(INT, B.avaliacao) = 8  THEN 1 ELSE 0 END) AS NOTA_8,
        SUM(CASE WHEN TRY_CONVERT(INT, B.avaliacao) = 7  THEN 1 ELSE 0 END) AS NOTA_7,
        SUM(CASE WHEN TRY_CONVERT(INT, B.avaliacao) = 6  THEN 1 ELSE 0 END) AS NOTA_6,
        SUM(CASE WHEN TRY_CONVERT(INT, B.avaliacao) = 5  THEN 1 ELSE 0 END) AS NOTA_5,
        SUM(CASE WHEN TRY_CONVERT(INT, B.avaliacao) = 4  THEN 1 ELSE 0 END) AS NOTA_4,
        SUM(CASE WHEN TRY_CONVERT(INT, B.avaliacao) = 3  THEN 1 ELSE 0 END) AS NOTA_3,
        SUM(CASE WHEN TRY_CONVERT(INT, B.avaliacao) = 2  THEN 1 ELSE 0 END) AS NOTA_2,
        SUM(CASE WHEN TRY_CONVERT(INT, B.avaliacao) = 1  THEN 1 ELSE 0 END) AS NOTA_1,

        COUNT(*) AS TOTAL_AVALIACOES,

        SUM(TRY_CONVERT(INT, B.avaliacao)) AS PONTOS,

        AVG(CAST(TRY_CONVERT(INT, B.avaliacao) AS DECIMAL(10,2))) AS MEDIA_AVALIACAO

    FROM TOMTICKET_CHAMADOS A
    INNER JOIN AVALIACAO_ATENDIMENTOS B
        ON A.id = B.id_atendimento

    WHERE TRY_CONVERT(INT, B.avaliacao) BETWEEN 1 AND 10
      AND A.creation_date >= @DATA_INICIO
      AND A.creation_date < DATEADD(DAY, 1, @DATA_FIM)

    GROUP BY A.operator_name

    ORDER BY TOTAL_AVALIACOES DESC;
END
GO